config/routes.rb
EpiCoderNotes::Application.routes.draw do
  root to: 'notes#index'
  resources :notes
end

app/models/author.rb
class Author < ActiveRecord::Base
  has_many :notes
  validates :name, :presence => true
end

app/models/note.rb
class Note < ActiveRecord::Base
  has_many :tags
  belongs_to :author
  validates :title, :presence => true
  validates :content, :presence => true
end

app/models/tag.rb
class Tag < ActiveRecord::Base
  belongs_to :note
  validates :tag, :presence => true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/notes_controller.rb
class NotesController < ApplicationController

  def index
    @notes = Note.all
  end

  def new
    @note = Note.new
  end

  def show
    @note = Note.find(params[:id])
  end

  def create
    @note = Note.new(note_params)
    if @note.save
      redirect_to notes_path, notice: "Thank you for Adding Notes!"
    else
      render "new"
    end
  end

  def edit
    @note = Note.find(params[:id])
  end

  def update
    @note = Note.find(params[:id])
    @note.update(note_params)
  end

  def note_params
    params.require(:note).permit(:title, :content, :tags_id, :author_id)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>EpiCoderNotes</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/notes/_form.html.erb
<%= form_for note do |f| %>
  Title: <%= f.text_field :title %><br />
  Content : <%= f.text_field :content %><br />
  <%= f.submit %>
<% end %>

app/views/notes/edit.html.erb
<%= render partial: "form", locals: {note: @note} %>

app/views/notes/index.html.erb
<div class="box">
<h1>Welcome to the EpiCoder Notes App</h1>
<h2>Here you can search and peruse Web Development Notes &amp; Resources by Junior Web Developers</h2>
</div>

<h2>Notes by Title</h2>
<ul><% @notes.each do |n| %>
<li><%= link_to n.title, note_path(n) %></li>
<%= n.content %>
<% end %>
</ul>


<p>Upload Notes here:</p>

<%= render partial: "form", locals: {note: Note.new} %>

app/views/notes/new.html.erb
%= form_for @note, url: {action: "create"}, html: {class: "nifty_form"} do |f| %>
  <%= f.text_field :title %>
  <%= f.text_area :body, size: "60x12" %>
  <%= f.submit "Create" %>
<% end %>


<h1>Add a Note:</h1>
<hr>
<form id="new-note" action='/notes' method="post">
  <%= render('form') %>
</form>
<div class="clear"></div>

app/views/notes/show.html.erb
<h1>Content</h1>
<%= @note.content %>


<br>
<%= link_to "Go Back", root_path %>


<h2>Options</h2>

<%= link_to "Edit Note", edit_note_path(@note) %>

app/views/notes/update.html.erb
<h1>Your content has been updated</h1>


<%= link_to "Go Back", root_path %>